language: python
sudo: required
dist: trusty

cache:
  directories:
    - /home/travis/docker

services:
  - docker

env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
    - DOCKER_COMPOSE="docker-compose -f docker-compose.travis.yml"

before_install:
  # list docker-engine versions
  - apt-cache madison docker-engine
  - "docker version"
  - "docker-compose version"
  - env
  - ./helpers/docker_cache.sh load_cache
  - "docker images -a"

# skip the builtin pip install
install: true
  - $DOCKER_COMPOSE build
  - "docker images -a"

before_script:
  - $DOCKER_COMPOSE up -d

script:
  - $DOCKER_COMPOSE run --rm -u root web sh -c 'pip3 install coverage && su pycroft -c "nosetests --with-xunit --with-coverage --cover-erase --cover-branches --cover-package=web,pycroft,legacy"'

before_cache:
  - ./helpers/docker_cache.sh save_cache
